const $=id=>document.getElementById(id);
let catalog=[],filter='all',sortMode='id',tagFilter='all',multi=false,selected=new Set(),current=null,prefs={},tagMeta={},syncState={paired:null,inventory:{},hasSnapshot:false,lastSync:''};
const STORE='nikkeTrackerV2',OLD_STORE='nikkeTrackerV1',TAG_STORE='nikkeTrackerTagMetaV1',SYNC_STORE='nikkeTrackerSyncV1';
const I={
 es:{all:'Todos',owned:'Con mods',empty:'Sin mods',mods:'con mods',variants:'variantes',nores:'No hay resultados',auto:'Automática',normal:'No NPC / Extra',npcOpt:'NPC / Extra',settings:'Configuración',pairTitle:'Sincronización con PC',notPaired:'No vinculado',paired:'Vinculado con',last:'Última sincronización',sync:'Sincronizar ahora',unpair:'Desvincular',syncOk:'Sincronización completada',syncFail:'No se pudo sincronizar',manual:'Vincular manualmente',data:'Datos locales',catalog:'Catálogo',notes:'Notas',tags:'Etiquetas',add:'Agregar',class:'Clasificación',syncHint:'Inventario del PC',manualHint:'Marcadores manuales',pcOffline:'Datos guardados del PC',syncing:'Sincronizando...',pairOk:'PC vinculado. Sincronizando...',badPair:'Enlace de vinculación no válido',reset:'Borrar datos locales'},
 en:{all:'All',owned:'With mods',empty:'No mods',mods:'with mods',variants:'variants',nores:'No results',auto:'Automatic',normal:'Not NPC / Extra',npcOpt:'NPC / Extra',settings:'Settings',pairTitle:'PC sync',notPaired:'Not paired',paired:'Paired with',last:'Last sync',sync:'Sync now',unpair:'Unpair',syncOk:'Sync completed',syncFail:'Could not sync',manual:'Pair manually',data:'Local data',catalog:'Catalog',notes:'Notes',tags:'Tags',add:'Add',class:'Classification',syncHint:'PC inventory',manualHint:'Manual markers',pcOffline:'Saved PC data',syncing:'Syncing...',pairOk:'PC paired. Syncing...',badPair:'Invalid pairing link',reset:'Delete local data'}
};
function lang(){return localStorage.getItem('nikkeLang')||'es'};const t=k=>I[lang()][k]||k;
function readJson(k,fallback){try{return JSON.parse(localStorage.getItem(k)||'')||fallback}catch(_e){return fallback}}
function load(){prefs=readJson(STORE,{});if(!Object.keys(prefs).length)prefs=readJson(OLD_STORE,{});tagMeta=readJson(TAG_STORE,{});syncState=Object.assign({paired:null,inventory:{},hasSnapshot:false,lastSync:''},readJson(SYNC_STORE,{}));ensureTagMetaFromPrefs()}
function savePrefs(){localStorage.setItem(STORE,JSON.stringify(prefs))}function saveTags(){localStorage.setItem(TAG_STORE,JSON.stringify(tagMeta))}function saveSync(){localStorage.setItem(SYNC_STORE,JSON.stringify(syncState))}
function data(k){return prefs[k]||(prefs[k]={actions:{},tags:[],notes:'',class:'auto'})}
function ensureTagMetaFromPrefs(){let changed=false;Object.keys(prefs).forEach(k=>{const tags=Array.isArray(prefs[k]?.tags)?prefs[k].tags:[];if(!tags.length)return;const b=tagMeta[k]||(tagMeta[k]={});tags.forEach(tag=>{const norm=String(tag).trim().toLowerCase();if(norm&&!b[norm]){b[norm]={tag:String(tag).trim(),present:true,updated_at:1};changed=true}})});if(changed)saveTags()}
function currentTags(k){const b=tagMeta[k]||{};return Object.values(b).filter(x=>x&&x.present&&x.tag).map(x=>x.tag).sort((a,b)=>a.localeCompare(b))}
function setTag(k,tag,present){tag=String(tag||'').trim().replace(/\s+/g,' ').slice(0,40);if(!tag)return false;const norm=tag.toLowerCase(),b=tagMeta[k]||(tagMeta[k]={});b[norm]={tag,present:!!present,updated_at:Date.now()};saveTags();return true}
function mergeTagMeta(remote){if(!remote||typeof remote!=='object')return;let changed=false;Object.entries(remote).forEach(([k,bucket])=>{if(!bucket||typeof bucket!=='object')return;const local=tagMeta[k]||(tagMeta[k]={});Object.entries(bucket).forEach(([norm,meta])=>{if(!meta||typeof meta!=='object'||!meta.tag)return;const r=Number(meta.updated_at||0),l=Number(local[norm]?.updated_at||0);if(r>l){local[norm]={tag:String(meta.tag),present:!!meta.present,updated_at:r};changed=true}})});if(changed)saveTags()}
function npcOf(c){const d=data(c.key);if(d.class==='npc')return true;if(d.class==='normal')return false;const inv=syncState.inventory?.[c.key];if(inv&&typeof inv.is_npc_extra==='boolean')return inv.is_npc_extra;return !!c.npcExtra}
function inv(c){return syncState.inventory?.[c.key]||null}function countAction(c,a){const i=inv(c);if(syncState.hasSnapshot)return Number(i?.counts?.[a]||0);return data(c.key).actions?.[a]?1:0}
function has(c,a){return countAction(c,a)>0}function owned(c){return actionsFor(c).some(a=>has(c,a))}function actionsFor(c){return npcOf(c)?['standing']:['aim','cover','standing']}
function conflictAction(c,a){return !!inv(c)?.conflicts?.includes(a)}
function esc(s){return String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]))}function numericId(x){return /^\d+$/.test(x)?Number(x):999999}
function toast(msg){const x=$('toast');x.textContent=msg;x.classList.remove('hidden');clearTimeout(window.__toast);window.__toast=setTimeout(()=>x.classList.add('hidden'),2600)}
function nativeCached(key){try{return window.AndroidBridge?.getCachedImage(key)||''}catch(_e){return''}}
function imageHtml(c,cls=''){const urls=Array.isArray(c.images)?c.images.filter(Boolean):[];const cached=nativeCached(c.key);const src=cached||urls[0]||'';return `<img class="${cls}" loading="lazy" decoding="async" referrerpolicy="no-referrer" src="${esc(src)}" data-key="${esc(c.key)}" data-images='${esc(JSON.stringify(urls))}' data-idx="${cached?-1:0}" onerror="imgFail(this)">`}
window.imgFail=function(img){let arr=[];try{arr=JSON.parse(img.dataset.images||'[]')}catch(_e){}let i=Number(img.dataset.idx||0)+1;if(i<arr.length){img.dataset.idx=i;img.src=arr[i];return}if(!img.dataset.nativeTried&&window.AndroidBridge){img.dataset.nativeTried='1';try{const local=AndroidBridge.cacheImage(img.dataset.key||'',JSON.stringify(arr));if(local){img.src=local;return}}catch(_e){}}img.style.display='none';const p=img.parentElement;p.classList.add('noimg');if(!p.querySelector('.placeholder'))p.insertAdjacentHTML('beforeend','<div class="placeholder">◇</div>')};
function filtered(){const q=$('search').value.trim().toLowerCase();let a=catalog.filter(c=>{if(q&&!`${c.name} ${c.id} ${c.version}`.toLowerCase().includes(q))return false;if(filter==='owned'&&!owned(c))return false;if(filter==='empty'&&owned(c))return false;if(filter==='npc'&&!npcOf(c))return false;const tg=currentTags(c.key);if(tagFilter==='untagged'&&tg.length)return false;if(tagFilter!=='all'&&tagFilter!=='untagged'&&!tg.includes(tagFilter))return false;return true});if(sortMode==='name')a.sort((x,y)=>x.name.localeCompare(y.name));else if(sortMode==='owned')a.sort((x,y)=>(Number(owned(y))-Number(owned(x)))||numericId(x.id)-numericId(y.id)||x.version.localeCompare(y.version));else a.sort((x,y)=>numericId(x.id)-numericId(y.id)||x.id.localeCompare(y.id)||x.version.localeCompare(y.version));return a}
function allTags(){return [...new Set(catalog.flatMap(c=>currentTags(c.key)))].sort((a,b)=>a.localeCompare(b))}function refreshTagFilter(){const cur=tagFilter;$('tagFilter').innerHTML=`<option value="all">${lang()==='es'?'Todas las etiquetas':'All tags'}</option><option value="untagged">${lang()==='es'?'Sin etiquetas':'Untagged'}</option>`+allTags().map(x=>`<option value="${esc(x)}">${esc(x)}</option>`).join('');if([...$('tagFilter').options].some(o=>o.value===cur))$('tagFilter').value=cur;else tagFilter='all'}
function actionLabel(a){return a==='aim'?'Aim':a==='cover'?'Cover':'Standing'}
function actionPills(c){return actionsFor(c).map(a=>{const n=countAction(c,a),cf=conflictAction(c,a);return `<span class="actionpill ${n?'on':''} ${cf?'conflict':''}">${actionLabel(a)}${n?` ${n}`:''}${cf?' ⚠':''}</span>`}).join('')}
function render(){refreshTagFilter();const a=filtered();$('count').textContent=`${a.length} / ${catalog.length}`;const own=catalog.filter(owned).length;$('summary').textContent=`${own} ${t('mods')} · ${catalog.length} ${t('variants')}`;$('grid').innerHTML=a.length?a.map(c=>`<button type="button" class="card ${selected.has(c.key)?'selected':''}" data-k="${esc(c.key)}" onclick="cardTap(event,'${esc(c.key)}')">${multi?`<div class="checkpick">${selected.has(c.key)?'✓':''}</div>`:''}<div class="portrait">${imageHtml(c)}</div><div class="cardbody"><div class="name">${esc(c.name)}</div><div class="meta">ID ${esc(c.id)} · Ver ${esc(c.version)}</div>${npcOf(c)?'<span class="npc">NPC / Extra</span>':''}<div class="actionsmini">${actionPills(c)}</div><div class="tagmini">${currentTags(c.key).slice(0,2).map(x=>`<span class="tag">${esc(x)}</span>`).join('')}</div></div></button>`).join(''):`<div class="empty">${t('nores')}</div>`;updateBulk();renderSyncStatus()}
window.cardTap=function(ev,k){ev.preventDefault();ev.stopPropagation();if(multi){selected.has(k)?selected.delete(k):selected.add(k);render()}else openDetail(k)};
function renderActions(){const c=current;if(!c)return;const readOnly=syncState.hasSnapshot;$('actions').innerHTML=actionsFor(c).map(a=>{const n=countAction(c,a);if(readOnly)return `<div class="actionrow"><b>${actionLabel(a)}</b><span class="readonlycount">${n}${conflictAction(c,a)?' ⚠':''}</span></div>`;return `<div class="actionrow"><b>${actionLabel(a)}</b><button class="toggle ${has(c,a)?'on':''}" data-a="${a}"><i></i></button></div>`}).join('');if(!readOnly)document.querySelectorAll('.toggle').forEach(b=>b.onclick=()=>{const d=data(c.key);d.actions[b.dataset.a]=!d.actions[b.dataset.a];savePrefs();renderActions();render()})}
function renderSyncedMods(){if(!current)return;const i=inv(current);if(!syncState.hasSnapshot){$('syncedMods').innerHTML='';return}const groups=actionsFor(current).map(a=>{const mods=(i?.mods||[]).filter(m=>m.action===a);if(!mods.length)return'';return `<div class="modgroup"><div class="modgrouphead"><span>${actionLabel(a)}</span><span>${mods.length}${conflictAction(current,a)?' ⚠':''}</span></div>${mods.map(m=>`<div class="moditem"><div class="modname">${esc(m.name||m.file_name||'Mod')}</div><div class="modmeta">${esc(m.author?`Autor: ${m.author}`:(m.file_name||''))}</div></div>`).join('')}</div>`}).join('');$('syncedMods').innerHTML=groups||`<div class="small">${lang()==='es'?'Sin mods sincronizados para esta variante.':'No synced mods for this variant.'}</div>`}
function openDetail(k){current=catalog.find(c=>c.key===k);if(!current)return;const d=data(k);$('detailName').textContent=current.name;$('detailId').textContent=`ID ${current.id} · Ver ${current.version}`;const wrap=$('detailImg').parentElement;wrap.innerHTML=imageHtml(current,'detailimage');wrap.firstElementChild.id='detailImg';$('npcBadge').innerHTML=npcOf(current)?'<span class="npc">NPC / Extra</span>':'';$('classSelect').value=d.class||'auto';$('notes').value=d.notes||'';renderActions();renderSyncedMods();renderDetailTags();$('modal').classList.remove('hidden')}
function renderDetailTags(){if(!current)return;const tg=currentTags(current.key);$('tagList').innerHTML=tg.map(x=>`<span class="tag">${esc(x)} <button data-t="${esc(x)}">×</button></span>`).join('');$('tagList').querySelectorAll('button').forEach(b=>b.onclick=()=>{setTag(current.key,b.dataset.t,false);renderDetailTags();render()})}
function addTagTo(keys,tag,present){tag=tag.trim();if(!tag)return;keys.forEach(k=>setTag(k,tag,present));render()}
function updateBulk(){$('selectedCount').textContent=`${selected.size} ${lang()==='es'?'seleccionados':'selected'}`;$('bulk').classList.toggle('hidden',!multi)}
function parsePairUri(value){try{const u=new URL(value);if(u.protocol!=='nikkemodtracker:'||u.hostname!=='pair')return null;const host=u.searchParams.get('host'),token=u.searchParams.get('token'),name=u.searchParams.get('name')||'PC';if(!host||!token)return null;return{host:host.replace(/\/$/,''),token,name}}catch(_e){return null}}
function handlePairFromQuery(){const q=new URLSearchParams(location.search);const host=q.get('pairHost'),token=q.get('pairToken');if(host&&token){syncState.paired={host:host.replace(/\/$/,''),token,name:q.get('pairName')||'PC'};saveSync();toast(t('pairOk'));setTimeout(syncNow,300)}}
function renderSyncStatus(){const p=syncState.paired;if($('pairStatus'))$('pairStatus').textContent=p?`${t('paired')} ${p.name||'PC'}`:t('notPaired');if($('pairHost'))$('pairHost').textContent=p?.host||'—';if($('lastSync'))$('lastSync').textContent=`${t('last')}: ${syncState.lastSync||'—'}`;$('syncNowBtn')&&($('syncNowBtn').disabled=!p);$('unpairBtn')&&($('unpairBtn').disabled=!p);if($('syncQuickBtn'))$('syncQuickBtn').style.opacity=p?'1':'.45';const b=$('syncBanner');if(b){if(syncState.hasSnapshot){b.textContent=`${t('pcOffline')}: ${syncState.lastSync||'—'}`;b.classList.remove('hidden')}else b.classList.add('hidden')}}
async function syncNow(){const p=syncState.paired;if(!p){toast(t('notPaired'));return}toast(t('syncing'));try{const url=`${p.host}/v1/sync?token=${encodeURIComponent(p.token)}`;const r=await fetch(url,{method:'POST',headers:{'Content-Type':'application/json','X-NIKKE-Token':p.token},body:JSON.stringify({tags:tagMeta}),cache:'no-store'});if(!r.ok)throw new Error(`HTTP ${r.status}`);const out=await r.json();if(!out.ok)throw new Error(out.error||'sync failed');mergeTagMeta(out.tags||{});syncState.inventory=out.inventory||{};syncState.hasSnapshot=true;syncState.lastSync=new Date().toLocaleString(lang()==='es'?'es-CL':'en-US');saveSync();render();if(current)openDetail(current.key);toast(t('syncOk'))}catch(e){toast(`${t('syncFail')}: ${e.message||e}`);renderSyncStatus()}}
function applyLanguage(){const es=lang()==='es';$('search').placeholder=es?'Buscar nombre, ID o Ver...':'Search name, ID or Ver...';$('multiBtn').textContent=es?'☑ Seleccionar varios':'☑ Select multiple';$('language').value=lang();[['all',es?'Todos':'All'],['owned',es?'Con mods':'With mods'],['empty',es?'Sin mods':'No mods'],['npc','NPC / Extra']].forEach(([f,txt])=>{const b=document.querySelector(`[data-f="${f}"]`);if(b)b.textContent=txt});$('settingsTitle').textContent=t('settings');$('syncTitle').textContent=t('pairTitle');$('syncNowBtn').textContent=`↻ ${t('sync')}`;$('unpairBtn').textContent=t('unpair');$('manualPairSummary').textContent=t('manual');$('dataTitle').textContent=t('data');$('catalogTitle').textContent=t('catalog');$('notesLabel').textContent=t('notes');$('tagsLabel').textContent=t('tags');$('addTag').textContent=t('add');$('classLabel').textContent=t('class');$('resetBtn').textContent=t('reset');$('classSelect').options[0].text=t('auto');$('classSelect').options[1].text=t('normal');$('classSelect').options[2].text=t('npcOpt');render()}
function bind(){$('search').oninput=render;$('sort').onchange=e=>{sortMode=e.target.value;render()};$('tagFilter').onchange=e=>{tagFilter=e.target.value;render()};$('filters').onclick=e=>{const b=e.target.closest('button');if(!b)return;filter=b.dataset.f;document.querySelectorAll('#filters button').forEach(x=>x.classList.toggle('active',x===b));render()};$('multiBtn').onclick=()=>{multi=!multi;if(!multi)selected.clear();render()};$('selectVisible').onclick=()=>{filtered().forEach(c=>selected.add(c.key));render()};$('clearSelected').onclick=()=>{selected.clear();render()};$('addBulk').onclick=()=>{addTagTo([...selected],$('bulkTag').value,true);$('bulkTag').value=''};$('removeBulk').onclick=()=>{addTagTo([...selected],$('bulkTag').value,false);$('bulkTag').value=''};$('close').onclick=()=>{$('notes').dispatchEvent(new Event('change'));$('modal').classList.add('hidden')};$('modal').onclick=e=>{if(e.target===$('modal'))$('close').click()};$('classSelect').onchange=e=>{data(current.key).class=e.target.value;savePrefs();openDetail(current.key);render()};$('notes').onchange=e=>{if(current){data(current.key).notes=e.target.value;savePrefs()}};$('addTag').onclick=()=>{if(current&&setTag(current.key,$('tagInput').value,true)){$('tagInput').value='';renderDetailTags();render()}};$('settingsBtn').onclick=()=>{$('catalogView').classList.add('hidden');$('settingsView').classList.remove('hidden');renderSyncStatus()};$('backSettings').onclick=()=>{$('settingsView').classList.add('hidden');$('catalogView').classList.remove('hidden')};$('language').onchange=e=>{localStorage.setItem('nikkeLang',e.target.value);applyLanguage()};$('syncNowBtn').onclick=syncNow;$('syncQuickBtn').onclick=syncNow;$('unpairBtn').onclick=()=>{syncState.paired=null;saveSync();renderSyncStatus();toast(t('notPaired'))};$('pairUrlBtn').onclick=()=>{const p=parsePairUri($('pairUrlInput').value.trim());if(!p){toast(t('badPair'));return}syncState.paired=p;saveSync();$('pairUrlInput').value='';renderSyncStatus();syncNow()};$('resetBtn').onclick=()=>{if(confirm(lang()==='es'?'¿Borrar marcadores, etiquetas, notas e inventario sincronizado?':'Delete markers, tags, notes and synced inventory?')){localStorage.removeItem(STORE);localStorage.removeItem(OLD_STORE);localStorage.removeItem(TAG_STORE);localStorage.removeItem(SYNC_STORE);prefs={};tagMeta={};syncState={paired:null,inventory:{},hasSnapshot:false,lastSync:''};render();renderSyncStatus()}}}
window.androidBack=function(){if(!$('modal').classList.contains('hidden')){$('close').click();return true}if(!$('settingsView').classList.contains('hidden')){$('backSettings').click();return true}return false};
async function init(){load();bind();applyLanguage();try{const r=await fetch('catalog.json');const p=await r.json();catalog=p.characters||[];$('catalogInfo').textContent=`${p.count||catalog.length} entradas · ${p.version||''}`;render()}catch(e){$('grid').innerHTML=`<div class="empty">Error: ${esc(e.message||e)}</div>`}handlePairFromQuery();renderSyncStatus()}
init();
